// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScgtECFaf5OEXFCXR4LErgKtVTW9HP0w',
    appId: '1:810717136030:web:198a8e40007cc064de278f',
    messagingSenderId: '810717136030',
    projectId: 'clubhub-c4d71',
    authDomain: 'clubhub-c4d71.firebaseapp.com',
    storageBucket: 'clubhub-c4d71.appspot.com',
    measurementId: 'G-VF3YJ6D1X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgfGX-Zqh5C4C6kGePGTWa1umC6jL0ps',
    appId: '1:810717136030:android:10d9994092a8f9eede278f',
    messagingSenderId: '810717136030',
    projectId: 'clubhub-c4d71',
    storageBucket: 'clubhub-c4d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlBjd6EFhqsR3hdjJTGcxqsm4ZbNMIwAg',
    appId: '1:810717136030:ios:d9018d1e03ff8902de278f',
    messagingSenderId: '810717136030',
    projectId: 'clubhub-c4d71',
    storageBucket: 'clubhub-c4d71.appspot.com',
    iosBundleId: 'com.example.clubhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScgtECFaf5OEXFCXR4LErgKtVTW9HP0w',
    appId: '1:810717136030:web:484e6c56502ad7c8de278f',
    messagingSenderId: '810717136030',
    projectId: 'clubhub-c4d71',
    authDomain: 'clubhub-c4d71.firebaseapp.com',
    storageBucket: 'clubhub-c4d71.appspot.com',
    measurementId: 'G-EGF9SYWNLR',
  );
}
